// src/driver/client/web/views/Workbench/index.tsx
import { observer } from 'mobx-react-lite';
import { container } from 'tsyringe';

import { Workbench } from '@domain/client/app/model/workbench';

import Mosaic from './Mosaic';
import Tile from './Tile';
import TopBar from './TopBar';

export default observer(function WorkbenchView() {
  const { root } = container.resolve(Workbench);

  return (
    <div className="flex h-full min-w-0 grow flex-col overflow-hidden">
      <TopBar />
      <Mosaic root={root} renderTile={(id) => <Tile id={id} />}>
        <div className="h-full">空空如也</div>
      </Mosaic>
    </div>
  );
});

// src/driver/client/web/view/Workbench/index.tsx
import { Show } from 'solid-js';
import { Splitter } from '@ark-ui/solid';
import Workbench from '#domain/client/app/model/Workbench';
import container from '#utils/singletonContainer';

import TileNode from './TileNode';
import Welcome from './Welcome';

export default function WorkbenchView(props: { panelId: string }) {
  const workbench = container.resolve(Workbench);

  return (
    <Splitter.Panel id={props.panelId} class="flex flex-col">
      <Show when={workbench.root} fallback={<Welcome />}>
        {(tile) => <TileNode tile={tile()} />}
      </Show>
    </Splitter.Panel>
  );
}
